// <auto-generated />
using System;
using AspNetCoreNLayeredArchitecture.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreNLayeredArchitecture.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240605105356_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.4.24267.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4402),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kalemler"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4404),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Defterler"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4405),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kitaplar"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4407),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çantalar"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4408),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kırtasiye"
                        });
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4711),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Pilot Kalem",
                            Price = 12.50m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4713),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kurşun Kalem",
                            Price = 5.50m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4715),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Tükenmez Kalem",
                            Price = 15.50m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4717),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kareli Defter",
                            Price = 7.50m,
                            Stock = 400
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4718),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çizgili Defter",
                            Price = 7.50m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4720),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "A5 Defter",
                            Price = 12.50m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4722),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "A4 Defter",
                            Price = 15.50m,
                            Stock = 250
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4723),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Düz Yazı Defter",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4725),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Harita Metot Defter",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4726),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Matematik 1",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4729),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Matematik 2",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4730),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Matematik 3",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4732),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fizik 1",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4734),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fizik 2",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4735),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Fizik 3",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4737),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kimya 1",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4738),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kimya 2",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4740),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kimya 3",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4741),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sırt Çantası",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4743),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bilgisayar Çantası",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4744),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor Çantası",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4746),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Beslenme Çantası",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4747),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kalem Kutusu",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4749),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Silgi",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4750),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kalemtraş",
                            Price = 10.50m,
                            Stock = 350
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4752),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kurşun",
                            Price = 10.50m,
                            Stock = 350
                        });
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.ProductFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Height")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Width")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Kırmızı",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4590),
                            Height = 100,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 1,
                            Width = 50
                        },
                        new
                        {
                            Id = 2,
                            Color = "Mavi",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4592),
                            Height = 150,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 2,
                            Width = 60
                        },
                        new
                        {
                            Id = 3,
                            Color = "Yeşil",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4594),
                            Height = 200,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 3,
                            Width = 70
                        },
                        new
                        {
                            Id = 4,
                            Color = "Siyah",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4596),
                            Height = 250,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 4,
                            Width = 80
                        },
                        new
                        {
                            Id = 5,
                            Color = "Beyaz",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4597),
                            Height = 300,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 5,
                            Width = 90
                        },
                        new
                        {
                            Id = 6,
                            Color = "Sarı",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4599),
                            Height = 350,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 6,
                            Width = 100
                        },
                        new
                        {
                            Id = 7,
                            Color = "Pembe",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4600),
                            Height = 400,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 7,
                            Width = 110
                        },
                        new
                        {
                            Id = 8,
                            Color = "Mor",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4601),
                            Height = 450,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 8,
                            Width = 120
                        },
                        new
                        {
                            Id = 9,
                            Color = "Turuncu",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4603),
                            Height = 500,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 9,
                            Width = 130
                        },
                        new
                        {
                            Id = 10,
                            Color = "Gri",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4604),
                            Height = 550,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 10,
                            Width = 140
                        },
                        new
                        {
                            Id = 11,
                            Color = "Kahverengi",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4607),
                            Height = 600,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 11,
                            Width = 150
                        },
                        new
                        {
                            Id = 12,
                            Color = "Lacivert",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4608),
                            Height = 650,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 12,
                            Width = 160
                        },
                        new
                        {
                            Id = 13,
                            Color = "Bordo",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4610),
                            Height = 700,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 13,
                            Width = 170
                        },
                        new
                        {
                            Id = 14,
                            Color = "Pembe",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4611),
                            Height = 750,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 14,
                            Width = 180
                        },
                        new
                        {
                            Id = 15,
                            Color = "Siyah",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4613),
                            Height = 800,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 15,
                            Width = 190
                        },
                        new
                        {
                            Id = 16,
                            Color = "Beyaz",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4614),
                            Height = 850,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 16,
                            Width = 200
                        },
                        new
                        {
                            Id = 17,
                            Color = "Sarı",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4615),
                            Height = 900,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 17,
                            Width = 210
                        },
                        new
                        {
                            Id = 18,
                            Color = "Pembe",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4617),
                            Height = 950,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 18,
                            Width = 220
                        },
                        new
                        {
                            Id = 19,
                            Color = "Mor",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4618),
                            Height = 1000,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 19,
                            Width = 230
                        },
                        new
                        {
                            Id = 20,
                            Color = "Turuncu",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4620),
                            Height = 1050,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 20,
                            Width = 240
                        },
                        new
                        {
                            Id = 21,
                            Color = "Gri",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4621),
                            Height = 1100,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 21,
                            Width = 250
                        },
                        new
                        {
                            Id = 22,
                            Color = "Kahverengi",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4623),
                            Height = 1150,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 22,
                            Width = 260
                        },
                        new
                        {
                            Id = 23,
                            Color = "Lacivert",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4624),
                            Height = 1200,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 23,
                            Width = 270
                        },
                        new
                        {
                            Id = 24,
                            Color = "Bordo",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4626),
                            Height = 1250,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 24,
                            Width = 280
                        },
                        new
                        {
                            Id = 25,
                            Color = "Pembe",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4627),
                            Height = 1300,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 25,
                            Width = 290
                        },
                        new
                        {
                            Id = 26,
                            Color = "Siyah",
                            CreateAt = new DateTime(2024, 6, 5, 13, 53, 56, 288, DateTimeKind.Local).AddTicks(4628),
                            Height = 1350,
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = 26,
                            Width = 300
                        });
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.Product", b =>
                {
                    b.HasOne("AspNetCoreNLayeredArchitecture.Core.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.ProductFeature", b =>
                {
                    b.HasOne("AspNetCoreNLayeredArchitecture.Core.Product", "Product")
                        .WithOne("ProductFeature")
                        .HasForeignKey("AspNetCoreNLayeredArchitecture.Core.ProductFeature", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AspNetCoreNLayeredArchitecture.Core.Product", b =>
                {
                    b.Navigation("ProductFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
